// Generated by scripts/bundle-games.sh from games.json — do not edit.
window.GAMES_DATA = [
  {
    "slug": "ninth-inning",
    "title": "NINTH INNING",
    "genre": "BASEBALL",
    "status": "PRESS START",
    "icon": "baseball",
    "source": "https://ninthinning.onrender.com/"
  },
  {
    "slug": "phaser-wars",
    "title": "PHASER WARS",
    "genre": "ACTION",
    "status": "PRESS START",
    "icon": "phaser",
    "source": "https://phaser-wars.onrender.com/fightinggame.html"
  }
];
