#!/usr/bin/env bash
# Re-bundle each game from its Render deployment into ./games/<slug>/ so the
# launcher serves everything same-origin (fixes iOS standalone pop-out).
#
# Source of truth is games.json at the repo root. To add a new game, append
# an entry there; this script handles the rest.
set -euo pipefail
cd "$(dirname "$0")/.."

python3 <<'PY'
import json, pathlib, subprocess

games = json.loads(pathlib.Path("games.json").read_text())

# Fetch each game from its Render source URL into games/<slug>/index.html
for g in games:
    slug = g["slug"]
    src  = g["source"]
    out  = pathlib.Path(f"games/{slug}/index.html")
    out.parent.mkdir(parents=True, exist_ok=True)
    print(f"→ {slug}  ←  {src}")
    subprocess.run(
        ["curl", "-fsSL", "--max-time", "30", "-o", str(out), src],
        check=True,
    )

# Regenerate games.js — a synchronous <script src> shim of games.json. This
# is what the launcher actually reads. We use a .js file (not fetch) so the
# launcher works from file:// for local testing without a dev server.
pathlib.Path("games.js").write_text(
    "// Generated by scripts/bundle-games.sh from games.json — do not edit.\n"
    "window.GAMES_DATA = " + json.dumps(games, indent=2) + ";\n"
)
PY

python3 scripts/inject-back-button.py games/*/index.html
echo "done."
