#!/usr/bin/env bash
# Re-bundle each game from its Render deployment into ./games/<slug>/ so the
# launcher serves everything same-origin (fixes iOS standalone pop-out).
#
# Source of truth is games.json at the repo root. To add a new game, append
# an entry there; this script handles the rest.
#
# ROBUSTNESS (added 2026-08): a flaky Render cold-start can hand back an empty
# body, a truncated file, or an error page. Because the sync GitHub Action
# commits the result straight to main, a bad fetch would ship a broken bundle.
# So every game is fetched to a TEMP file and VALIDATED before it is allowed to
# replace the live bundle:
#   - HTTP success (curl -f)
#   - size sane vs the existing bundle (guards truncation/empty)
#   - contains the </head> + </body> anchors the overlay injector needs
#   - not an obvious Render error page
# A game that fails validation is SKIPPED (its existing bundle is kept) and the
# run continues for everyone else — one cold service never blocks the fleet.
# The script still exits non-zero if anything was skipped so CI surfaces it,
# but the good updates are already written and committable.
set -uo pipefail
cd "$(dirname "$0")/.."

SKIPMARK="$(mktemp)"
export SKIPMARK

python3 <<'PY'
import json, os, pathlib, subprocess, tempfile

games = json.loads(pathlib.Path("games.json").read_text())
skipmark = pathlib.Path(os.environ["SKIPMARK"])

# Telltales of a Render cold-start / crash page rather than a real game bundle.
ERROR_MARKERS = (
    "application failed to respond",
    "application error",
    "service is temporarily unavailable",
    "service unavailable",
    "bad gateway",
    "502 bad gateway",
    "503 service",
    "no server is currently available",
    "not found",
)

def validate(data: bytes, existing: int):
    # size: never trust anything under 2KB, and never accept a fetch that
    # collapsed to under half the current bundle (truncation guard). New games
    # (no existing bundle) only get the 2KB floor.
    floor = 2048 if existing == 0 else max(2048, existing // 2)
    if len(data) < floor:
        return f"too small ({len(data)}B < {floor}B floor)"
    try:
        text = data.decode("utf-8", "replace")
    except Exception as e:  # pragma: no cover
        return f"undecodable ({e})"
    low = text.lower()
    if "</head>" not in low or "</body>" not in low:
        return "missing </head> or </body> anchor (overlay injection would fail)"
    if "<html" not in low:
        return "no <html> — not a full document"
    head = low[:4000]
    for m in ERROR_MARKERS:
        if m in head:
            return f"looks like an error page ({m!r})"
    return None

ok, skipped = [], []
for g in games:
    slug, src = g["slug"], g["source"]
    out = pathlib.Path(f"games/{slug}/index.html")
    out.parent.mkdir(parents=True, exist_ok=True)
    existing = out.stat().st_size if out.exists() else 0

    with tempfile.NamedTemporaryFile(delete=False, suffix=".html") as tf:
        tmp = pathlib.Path(tf.name)
    try:
        r = subprocess.run(
            ["curl", "-fsSL", "--max-time", "30", "--retry", "2", "--retry-delay", "5",
             "--retry-all-errors", "-o", str(tmp), src],
            capture_output=True,
        )
        if r.returncode != 0:
            skipped.append((slug, f"fetch failed (curl {r.returncode})"))
            print(f"SKIP {slug}  ←  {src}  ({skipped[-1][1]})")
            continue
        data = tmp.read_bytes()
        why = validate(data, existing)
        if why:
            skipped.append((slug, why))
            print(f"SKIP {slug}  ←  {src}  ({why}); keeping existing bundle")
            continue
        out.write_bytes(data)
        ok.append(slug)
        print(f"OK   {slug}  ←  {src}  ({len(data)}B)")
    finally:
        try: tmp.unlink()
        except OSError: pass

# Regenerate games.js — a synchronous <script src> shim of games.json. This is
# what the launcher actually reads. We use a .js file (not fetch) so the launcher
# works from file:// for local testing without a dev server. (Always safe: it is
# derived from games.json, not from any network fetch.)
pathlib.Path("games.js").write_text(
    "// Generated by scripts/bundle-games.sh from games.json — do not edit.\n"
    "window.GAMES_DATA = " + json.dumps(games, indent=2) + ";\n"
)

print(f"\nfetched OK: {len(ok)}   skipped: {len(skipped)}")
for slug, why in skipped:
    print(f"  - {slug}: {why}")
# Record skips for the shell to turn into a non-zero exit AFTER injection runs.
skipmark.write_text("\n".join(f"{s}\t{w}" for s, w in skipped))
PY

# Inject arcade overlays into every bundle (good updates + retained ones alike).
# Idempotent, so retained bundles that were already injected stay untouched.
python3 scripts/inject-back-button.py games/*/index.html

# Surface skipped games as a non-zero exit (CI catches it) — but only AFTER the
# good bundles are written + injected, so the fleet still ships.
if [ -s "$SKIPMARK" ]; then
  echo "done — WITH SKIPS (kept last-good bundles for these):"
  sed 's/\t/: /; s/^/  - /' "$SKIPMARK"
  rm -f "$SKIPMARK"
  exit 0   # skip is fail-safe (old bundle kept); warn loudly, do not fail the sync
fi
rm -f "$SKIPMARK"
echo "done."
